---
- name: Playbook to deploy our application in kubernetes
  hosts: deployserver
  tasks:  
   - name: remove existing bashscripts directory and ignore task if bashscripts folder is not there
     ansible.builtin.shell:
       cmd: sudo rm -r bashscripts
     ignore_errors: yes    
       
   - name: create new bashscripts directory
     ansible.builtin.shell:
       cmd: sudo mkdir bashscripts         

   - name: clone bash scripts repo into server
     ansible.builtin.shell:
       cmd: sudo git clone https://github.com/sagarkakkalasworld/Day8.git
       chdir: bashscripts/

   - name: giving ownership to build.sh and giving excecuting permissions to deploy.sh
     ansible.builtin.shell:
       cmd: sudo chown ubuntu deploy.sh && sudo chmod 744 deploy.sh
       chdir: bashscripts/Day8/Bash

   - name: running script to make build
     ansible.builtin.shell: 
       cmd: ./deploy.sh
       chdir: bashscripts/Day8/Bash